Data Gathering

In [1]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\prerna kumari\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from tensorflow) (1.83.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\prerna kumari\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.6.15)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\prerna kumari\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\prerna kumari\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\prerna kumari\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\prerna kumari\appdata\roaming\python\python313\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

C:\Users\Prerna Kumari\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
data=pd.read_csv('twitter_training.csv')

In [4]:
data

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [5]:
data=data.sample(15000,random_state=42)

In [6]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one

In [7]:
data.shape

(15000, 4)

Data Exploration

In [8]:
data['Positive'].value_counts()

Positive
Negative      4488
Positive      4275
Neutral       3568
Irrelevant    2669
Name: count, dtype: int64

In [9]:
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    151
dtype: int64

In [10]:
data.duplicated().sum()

np.int64(127)

Data Cleaning

In [11]:
data.dropna()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one
...,...,...,...,...
7757,9333,Overwatch,Positive,i can play overwatch again (bad)
3887,1872,CallOfDutyBlackopsColdWar,Negative,The base weapons of black ops Cold War are so ...
22629,4275,CS-GO,Neutral,Don'don t just jump me... @CSGO... is medal. t...
66836,7044,johnson&johnson,Irrelevant,for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434,11284,TomClancysRainbowSix,Positive,New video later shoot premiere at 12 and its g...

In [12]:
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    151
dtype: int64

In [13]:
data.shape

(15000, 4)

In [14]:
data.drop_duplicates(inplace=True)

In [15]:
data.duplicated().sum()

np.int64(0)

In [16]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one

In [17]:
data.drop(columns=['2401','Borderlands'],inplace=True)

In [18]:
data.head()

         Positive im getting on borderlands and i will murder you all ,
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one

In [19]:
data.rename(
    columns={
        'Positive': 'Sentiment',
        'im getting on borderlands and i will murder you all ,': 'Tweets'
    },
    inplace=True
)

In [20]:
data.head()

        Sentiment                                             Tweets
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one

In [21]:
data['Sentiment'].value_counts()

Sentiment
Negative      4453
Positive      4231
Neutral       3546
Irrelevant    2643
Name: count, dtype: int64

In [22]:
data = data[
    (data['Sentiment'] == 'Positive') |
    (data['Sentiment'] == 'Negative') |
    (data['Sentiment'] == 'Neutral')
]

In [23]:
data['Sentiment'].value_counts()

Sentiment
Negative    4453
Positive    4231
Neutral     3546
Name: count, dtype: int64

In [24]:
data.head()

      Sentiment                                             Tweets
21704  Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008  Negative  Pay attention executive administrators. While ...
454    Positive                                                one
58076  Negative       @Rainbow6Game Server are Available in Xbox 🥺
40659  Positive  so Awesome siege attempt... strangest bleeding...

Feature Encoding

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
label=LabelEncoder()

In [27]:
data['Sentiment']=label.fit_transform(data['Sentiment'])

In [28]:
data

       Sentiment                                             Tweets
21704          2         Yo this looks LIT! Team:GO/Overwatch combo
47008          0  Pay attention executive administrators. While ...
454            2                                                one
58076          0       @Rainbow6Game Server are Available in Xbox 🥺
40659          2  so Awesome siege attempt... strangest bleeding...
...          ...                                                ...
57537          2  This is not my nice way of saying what GN with...
7757           2                   i can play overwatch again (bad)
3887           0  The base weapons of black ops Cold War are so ...
22629          1  Don'don t just jump me... @CSGO... is medal. t...
56434          2  New video later shoot premiere at 12 and its g...

[12230 rows x 2 columns]

In [29]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [30]:
tokenizer=Tokenizer()

In [31]:
data['Tweets'] = data['Tweets'].fillna('').astype(str)

In [32]:
tokenizer.fit_on_texts(data['Tweets'])

In [33]:
tokenizer.word_index

{'the': 1,
 'i': 2,
 'to': 3,
 'and': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'in': 8,
 'for': 9,
 'this': 10,
 'it': 11,
 'my': 12,
 'on': 13,
 'you': 14,
 'that': 15,
 'com': 16,
 'game': 17,
 'with': 18,
 'so': 19,
 'have': 20,
 'be': 21,
 'just': 22,
 'me': 23,
 'not': 24,
 'but': 25,
 'are': 26,
 'all': 27,
 'was': 28,
 'at': 29,
 '2': 30,
 'out': 31,
 'like': 32,
 'pic': 33,
 'twitter': 34,
 'your': 35,
 'from': 36,
 'get': 37,
 'now': 38,
 'as': 39,
 'we': 40,
 'good': 41,
 't': 42,
 'play': 43,
 'johnson': 44,
 'they': 45,
 'do': 46,
 'about': 47,
 'if': 48,
 'can': 49,
 'new': 50,
 'one': 51,
 'has': 52,
 'an': 53,
 'no': 54,
 'really': 55,
 'when': 56,
 "i'm": 57,
 'will': 58,
 'love': 59,
 'time': 60,
 'what': 61,
 'up': 62,
 'more': 63,
 'unk': 64,
 '3': 65,
 'some': 66,
 'why': 67,
 'still': 68,
 'shit': 69,
 'people': 70,
 "it's": 71,
 'or': 72,
 'co': 73,
 'by': 74,
 'been': 75,
 'how': 76,
 'https': 77,
 'amazon': 78,
 '’': 79,
 'microsoft': 80,
 'best': 81,
 'games': 82,
 'dead': 83,
 '1': 84,
 'facebook': 85,
 'fucking': 86,
 'playing': 87,
 'got': 88,
 'verizon': 89,
 'because': 90,
 'great': 91,
 'fuck': 92,
 'rhandlerr': 93,
 'go': 94,
 'red': 95,
 'even': 96,
 'please': 97,
 'xbox': 98,
 'who': 99,
 'see': 100,
 'them': 101,
 'us': 102,
 'home': 103,
 'back': 104,
 'much': 105,
 '5': 106,
 'only': 107,
 'google': 108,
 'going': 109,
 'there': 110,
 'had': 111,
 'am': 112,
 "can't": 113,
 'fix': 114,
 'nvidia': 115,
 's': 116,
 'borderlands': 117,
 'tv': 118,
 'would': 119,
 'their': 120,
 'after': 121,
 'fun': 122,
 'our': 123,
 '4': 124,
 'its': 125,
 'again': 126,
 'these': 127,
 'day': 128,
 'eamaddennfl': 129,
 'first': 130,
 'most': 131,
 'than': 132,
 'very': 133,
 'over': 134,
 "don't": 135,
 'fifa': 136,
 'wait': 137,
 'today': 138,
 'also': 139,
 'make': 140,
 'never': 141,
 '2020': 142,
 'here': 143,
 'pubg': 144,
 'redemption': 145,
 'then': 146,
 'twitch': 147,
 'know': 148,
 'nba2k': 149,
 'want': 150,
 'bad': 151,
 'ever': 152,
 'rainbow6game': 153,
 'think': 154,
 'thank': 155,
 'gta': 156,
 '…': 157,
 'he': 158,
 'amazing': 159,
 'every': 160,
 'damn': 161,
 'depot': 162,
 'work': 163,
 'year': 164,
 'ps5': 165,
 'played': 166,
 'thanks': 167,
 'legends': 168,
 'video': 169,
 'guys': 170,
 'x': 171,
 'getting': 172,
 'call': 173,
 'i’m': 174,
 'too': 175,
 'last': 176,
 'news': 177,
 'series': 178,
 'help': 179,
 "i've": 180,
 'any': 181,
 'world': 182,
 'warcraft': 183,
 'happy': 184,
 'down': 185,
 'into': 186,
 'well': 187,
 '10': 188,
 'while': 189,
 'black': 190,
 'league': 191,
 'v': 192,
 'being': 193,
 'years': 194,
 'u': 195,
 'overwatch': 196,
 'off': 197,
 'man': 198,
 'watch': 199,
 'looks': 200,
 'say': 201,
 'always': 202,
 'right': 203,
 'youtu': 204,
 'another': 205,
 'ghostrecon': 206,
 'live': 207,
 'did': 208,
 'finally': 209,
 'creed': 210,
 'stop': 211,
 'update': 212,
 'need': 213,
 'team': 214,
 'youtube': 215,
 'store': 216,
 'battlefield': 217,
 'actually': 218,
 'players': 219,
 'should': 220,
 'everyone': 221,
 'ass': 222,
 'via': 223,
 'money': 224,
 'made': 225,
 'his': 226,
 'look': 227,
 'next': 228,
 'fortnite': 229,
 'buy': 230,
 'csgo': 231,
 'way': 232,
 'big': 233,
 'hearthstone': 234,
 'win': 235,
 'duty': 236,
 'already': 237,
 'many': 238,
 'free': 239,
 'thing': 240,
 'better': 241,
 'could': 242,
 'which': 243,
 'take': 244,
 'since': 245,
 'playstation': 246,
 'were': 247,
 'come': 248,
 'health': 249,
 'awesome': 250,
 'wow': 251,
 'wtf': 252,
 'it’s': 253,
 'before': 254,
 'support': 255,
 'same': 256,
 'access': 257,
 'nice': 258,
 'something': 259,
 'bit': 260,
 'care': 261,
 'pc': 262,
 'hate': 263,
 'keep': 264,
 'such': 265,
 'her': 266,
 'playapex': 267,
 'other': 268,
 'online': 269,
 'done': 270,
 'gonna': 271,
 'trying': 272,
 'excited': 273,
 '20': 274,
 'having': 275,
 'ubisoft': 276,
 'ly': 277,
 'days': 278,
 'give': 279,
 'oh': 280,
 'stream': 281,
 '100': 282,
 'hey': 283,
 'baby': 284,
 'everything': 285,
 'pretty': 286,
 'both': 287,
 '6': 288,
 'cool': 289,
 'lot': 290,
 'looking': 291,
 'old': 292,
 'war': 293,
 'doing': 294,
 'long': 295,
 'check': 296,
 'account': 297,
 'does': 298,
 'where': 299,
 'top': 300,
 'start': 301,
 'life': 302,
 'im': 303,
 'someone': 304,
 'mobile': 305,
 'cyberpunk': 306,
 'through': 307,
 'card': 308,
 'nothing': 309,
 '7': 310,
 'pay': 311,
 'two': 312,
 'player': 313,
 'real': 314,
 'use': 315,
 'things': 316,
 'servers': 317,
 'him': 318,
 'powder': 319,
 'feel': 320,
 'dota': 321,
 'super': 322,
 'lol': 323,
 'working': 324,
 'phone': 325,
 'stupid': 326,
 'little': 327,
 'night': 328,
 'm': 329,
 'hope': 330,
 'those': 331,
 'service': 332,
 'problem': 333,
 'making': 334,
 'company': 335,
 'season': 336,
 'god': 337,
 'hours': 338,
 'almost': 339,
 'hell': 340,
 'makes': 341,
 'ops': 342,
 'yet': 343,
 'literally': 344,
 'until': 345,
 'week': 346,
 '2077': 347,
 'italy': 348,
 'probably': 349,
 'anyone': 350,
 'dont': 351,
 'miss': 352,
 'favorite': 353,
 'can’t': 354,
 '19': 355,
 'uk': 356,
 'cold': 357,
 'against': 358,
 'won': 359,
 'try': 360,
 'business': 361,
 'hard': 362,
 'release': 363,
 "doesn't": 364,
 'whole': 365,
 'absolutely': 366,
 'let': 367,
 'full': 368,
 'own': 369,
 'find': 370,
 'times': 371,
 'worst': 372,
 'gaming': 373,
 'lost': 374,
 'show': 375,
 'chance': 376,
 'trash': 377,
 'said': 378,
 'app': 379,
 'minutes': 380,
 'few': 381,
 'apex': 382,
 'fact': 383,
 'open': 384,
 '0': 385,
 'end': 386,
 'put': 387,
 'says': 388,
 'without': 389,
 'part': 390,
 'story': 391,
 'cant': 392,
 "that's": 393,
 'assassins': 394,
 'hit': 395,
 '2k': 396,
 'mode': 397,
 'interesting': 398,
 'stuff': 399,
 'far': 400,
 'console': 401,
 'using': 402,
 'ea': 403,
 'guy': 404,
 'sure': 405,
 'coming': 406,
 'ranked': 407,
 'wrong': 408,
 'gameplay': 409,
 'idea': 410,
 'ps4': 411,
 'callofduty': 412,
 'anything': 413,
 'gets': 414,
 'ban': 415,
 'tt': 416,
 'around': 417,
 'thought': 418,
 'maybe': 419,
 'order': 420,
 'selling': 421,
 'vaccine': 422,
 'data': 423,
 '30': 424,
 'reason': 425,
 'tell': 426,
 'friends': 427,
 '21': 428,
 'screen': 429,
 "you're": 430,
 'beautiful': 431,
 'perfect': 432,
 'million': 433,
 'soon': 434,
 'crazy': 435,
 'worth': 436,
 'enough': 437,
 '15': 438,
 'used': 439,
 'y’all': 440,
 'd': 441,
 'covid': 442,
 "y'all": 443,
 'sad': 444,
 'point': 445,
 'pro': 446,
 'madden': 447,
 'though': 448,
 'enjoy': 449,
 'tonight': 450,
 'w': 451,
 'p': 452,
 'bought': 453,
 'high': 454,
 'dota2': 455,
 'graphics': 456,
 'line': 457,
 'currently': 458,
 'went': 459,
 'talc': 460,
 "didn't": 461,
 'away': 462,
 'banned': 463,
 'watching': 464,
 'month': 465,
 'change': 466,
 'weekend': 467,
 'epic': 468,
 'may': 469,
 'system': 470,
 'forward': 471,
 'internet': 472,
 'second': 473,
 '12': 474,
 'playhearthstone': 475,
 'tried': 476,
 'ift': 477,
 'different': 478,
 'bro': 479,
 'feels': 480,
 'kill': 481,
 "i'll": 482,
 "assassin's": 483,
 'due': 484,
 'price': 485,
 'share': 486,
 'broken': 487,
 'based': 488,
 'latest': 489,
 'saying': 490,
 'grand': 491,
 'org': 492,
 'services': 493,
 'cause': 494,
 '”': 495,
 'able': 496,
 'job': 497,
 'don’t': 498,
 'ok': 499,
 'cs': 500,
 'pre': 501,
 'patch': 502,
 'took': 503,
 'comes': 504,
 'skin': 505,
 'character': 506,
 'definitely': 507,
 'ago': 508,
 'morning': 509,
 'server': 510,
 'mean': 511,
 'myself': 512,
 'homedepot': 513,
 'exciting': 514,
 'sorry': 515,
 'power': 516,
 'else': 517,
 'huge': 518,
 'terrible': 519,
 'myteam': 520,
 'wanna': 521,
 'n2k': 522,
 'instead': 523,
 'might': 524,
 'problems': 525,
 'despite': 526,
 'cod': 527,
 'level': 528,
 'post': 529,
 'came': 530,
 'sucks': 531,
 'gold': 532,
 'i’ve': 533,
 'started': 534,
 'beluba': 535,
 'must': 536,
 'net': 537,
 'apps': 538,
 'cards': 539,
 'read': 540,
 'rewards': 541,
 'content': 542,
 'finished': 543,
 'customer': 544,
 'anymore': 545,
 'products': 546,
 'she': 547,
 'wanted': 548,
 'windows': 549,
 'eu': 550,
 'during': 551,
 'guess': 552,
 'music': 553,
 '8': 554,
 'seems': 555,
 'event': 556,
 'leagueoflegends': 557,
 'updates': 558,
 'months': 559,
 'luck': 560,
 'ready': 561,
 'seen': 562,
 'needs': 563,
 'killed': 564,
 'tomorrow': 565,
 'achievement': 566,
 'dlvr': 567,
 'set': 568,
 '9': 569,
 'run': 570,
 'match': 571,
 'y': 572,
 'trailer': 573,
 'annoying': 574,
 'experience': 575,
 'later': 576,
 're': 577,
 'talk': 578,
 'remember': 579,
 'single': 580,
 "won't": 581,
 'r': 582,
 'die': 583,
 'holy': 584,
 'shot': 585,
 'seriously': 586,
 'name': 587,
 'error': 588,
 'list': 589,
 'design': 590,
 'ronnie2k': 591,
 'early': 592,
 'breakpoint': 593,
 'half': 594,
 '3080': 595,
 'hi': 596,
 'yo': 597,
 'hour': 598,
 'taken': 599,
 'step': 600,
 'living': 601,
 'yall': 602,
 'honestly': 603,
 'least': 604,
 'gone': 605,
 'rtx': 606,
 'three': 607,
 'found': 608,
 'edition': 609,
 "haven't": 610,
 'buying': 611,
 'number': 612,
 'completely': 613,
 'face': 614,
 'loved': 615,
 'warzone': 616,
 'earned': 617,
 'place': 618,
 'blizzard': 619,
 'sometimes': 620,
 'late': 621,
 'gen': 622,
 'easports': 623,
 'once': 624,
 'community': 625,
 'person': 626,
 'c': 627,
 'yes': 628,
 'e': 629,
 'videos': 630,
 'proud': 631,
 'believe': 632,
 'issue': 633,
 'don': 634,
 'book': 635,
 'class': 636,
 '•': 637,
 'issues': 638,
 'below': 639,
 'apple': 640,
 'together': 641,
 'hear': 642,
 'seeing': 643,
 'funny': 644,
 'teams': 645,
 'totally': 646,
 'small': 647,
 'called': 648,
 'movie': 649,
 'friend': 650,
 'keeps': 651,
 'fan': 652,
 'omg': 653,
 'birthday': 654,
 'pass': 655,
 'thinking': 656,
 'suck': 657,
 'bullshit': 658,
 'each': 659,
 'follow': 660,
 'code': 661,
 'city': 662,
 'hello': 663,
 'worse': 664,
 'ghost': 665,
 'review': 666,
 'complete': 667,
 'smh': 668,
 'less': 669,
 'kinda': 670,
 'major': 671,
 'released': 672,
 'retweet': 673,
 'under': 674,
 'sound': 675,
 'trump': 676,
 'switch': 677,
 'sick': 678,
 'canada': 679,
 'battle': 680,
 'leave': 681,
 'past': 682,
 'streaming': 683,
 'either': 684,
 'tech': 685,
 'bugs': 686,
 'understand': 687,
 'launch': 688,
 'incredible': 689,
 'join': 690,
 'india': 691,
 'tired': 692,
 'main': 693,
 "they're": 694,
 'daily': 695,
 'gotta': 696,
 '“': 697,
 'article': 698,
 'lmao': 699,
 'kills': 700,
 'running': 701,
 'cannot': 702,
 'link': 703,
 'yesterday': 704,
 'saw': 705,
 'odyssey': 706,
 'ai': 707,
 'action': 708,
 'instagram': 709,
 'deal': 710,
 'add': 711,
 'move': 712,
 'cute': 713,
 'received': 714,
 'bring': 715,
 'stock': 716,
 'gift': 717,
 'mind': 718,
 'joke': 719,
 'iphone': 720,
 'b': 721,
 'family': 722,
 'market': 723,
 'waiting': 724,
 'garbage': 725,
 "we're": 726,
 'starting': 727,
 'kind': 728,
 'slow': 729,
 'mad': 730,
 'house': 731,
 've': 732,
 'stay': 733,
 'global': 734,
 "what's": 735,
 'ubisoftsupport': 736,
 'means': 737,
 "let's": 738,
 'drop': 739,
 'moment': 740,
 'girl': 741,
 'entire': 742,
 'franchise': 743,
 'that’s': 744,
 'goes': 745,
 'moments': 746,
 'fps': 747,
 'technology': 748,
 'truly': 749,
 'playoverwatch': 750,
 'points': 751,
 'absolute': 752,
 'glad': 753,
 'rockstargames': 754,
 'social': 755,
 'tho': 756,
 'spent': 757,
 'id': 758,
 'page': 759,
 'commission': 760,
 'quite': 761,
 'warfare': 762,
 'coronavirus': 763,
 'hyped': 764,
 'weeks': 765,
 'o': 766,
 'insane': 767,
 'bug': 768,
 'original': 769,
 'car': 770,
 '14': 771,
 'ur': 772,
 'steam': 773,
 'history': 774,
 'cancer': 775,
 'special': 776,
 'item': 777,
 'left': 778,
 'users': 779,
 'hot': 780,
 'trust': 781,
 'sounds': 782,
 'sell': 783,
 '–': 784,
 'continue': 785,
 'j': 786,
 'close': 787,
 'okay': 788,
 'congratulations': 789,
 'decided': 790,
 'boy': 791,
 'easy': 792,
 'delayed': 793,
 'talking': 794,
 'break': 795,
 'final': 796,
 'fortnitegame': 797,
 'taking': 798,
 'toxic': 799,
 'pick': 800,
 'version': 801,
 'star': 802,
 'lots': 803,
 'walmart': 804,
 'women': 805,
 'sold': 806,
 'takes': 807,
 'wikipedia': 808,
 'turn': 809,
 'dear': 810,
 'crap': 811,
 'yeah': 812,
 'sony': 813,
 "there's": 814,
 'happened': 815,
 'kids': 816,
 'siege': 817,
 'welcome': 818,
 'decision': 819,
 'en': 820,
 'hero': 821,
 'poverty': 822,
 'ridiculous': 823,
 'modern': 824,
 'including': 825,
 'men': 826,
 'paid': 827,
 'knows': 828,
 'performance': 829,
 'told': 830,
 '99': 831,
 'enjoyed': 832,
 '24': 833,
 'redeeming': 834,
 'fans': 835,
 'connection': 836,
 'shooting': 837,
 'wins': 838,
 'digital': 839,
 'report': 840,
 'worked': 841,
 'safe': 842,
 'mut': 843,
 'bitch': 844,
 'l': 845,
 'date': 846,
 'head': 847,
 'massive': 848,
 'feeling': 849,
 'plus': 850,
 'geforce': 851,
 'true': 852,
 'packs': 853,
 'works': 854,
 'box': 855,
 'wild': 856,
 'forever': 857,
 'heart': 858,
 'death': 859,
 'biggest': 860,
 'f': 861,
 'security': 862,
 'nba': 863,
 'shut': 864,
 'yourself': 865,
 'low': 866,
 'longer': 867,
 'died': 868,
 'dope': 869,
 'sense': 870,
 'beta': 871,
 'created': 872,
 'fight': 873,
 'stuck': 874,
 'fast': 875,
 'test': 876,
 'stopped': 877,
 'felt': 878,
 'china': 879,
 'channel': 880,
 'plan': 881,
 'boring': 882,
 'art': 883,
 'plz': 884,
 '11': 885,
 'state': 886,
 'gpu': 887,
 'unit': 888,
 'nfl': 889,
 'school': 890,
 'n': 891,
 'search': 892,
 'learning': 893,
 'listen': 894,
 'ordered': 895,
 'important': 896,
 'drive': 897,
 'sweet': 898,
 'hand': 899,
 'hold': 900,
 'somehow': 901,
 'plays': 902,
 'skins': 903,
 'platform': 904,
 'delivery': 905,
 'heard': 906,
 'current': 907,
 'email': 908,
 'option': 909,
 'developers': 910,
 'between': 911,
 'football': 912,
 '13': 913,
 'till': 914,
 'matter': 915,
 'cry': 916,
 'powerful': 917,
 'map': 918,
 'lose': 919,
 'enjoying': 920,
 'spend': 921,
 'rather': 922,
 'wish': 923,
 'future': 924,
 'crashing': 925,
 'ya': 926,
 '000': 927,
 'valorant': 928,
 'racist': 929,
 '60': 930,
 'rt': 931,
 'summoners': 932,
 'word': 933,
 'demon': 934,
 'favourite': 935,
 'pls': 936,
 'fixed': 937,
 'controller': 938,
 'quit': 939,
 'bc': 940,
 'recon': 941,
 'rest': 942,
 'log': 943,
 'couple': 944,
 'chinese': 945,
 'tf': 946,
 'giving': 947,
 'government': 948,
 '50': 949,
 'inside': 950,
 'ppl': 951,
 'eahelp': 952,
 'dark': 953,
 'behind': 954,
 'calling': 955,
 'theft': 956,
 '25': 957,
 'calls': 958,
 '16': 959,
 'trial': 960,
 'especially': 961,
 'companies': 962,
 'greatest': 963,
 'within': 964,
 'website': 965,
 'random': 966,
 'white': 967,
 'brand': 968,
 'sales': 969,
 'suddenly': 970,
 'imagine': 971,
 'fantastic': 972,
 'control': 973,
 'party': 974,
 'program': 975,
 'gave': 976,
 'fake': 977,
 'cuz': 978,
 'towards': 979,
 'king': 980,
 'decent': 981,
 'edge': 982,
 'quality': 983,
 'tweet': 984,
 'shitty': 985,
 'ahead': 986,
 'pandemic': 987,
 'short': 988,
 'monday': 989,
 'create': 990,
 'customers': 991,
 'ball': 992,
 'happens': 993,
 "isn't": 994,
 'features': 995,
 'explain': 996,
 'af': 997,
 'dumb': 998,
 'finish': 999,
 'g': 1000,
 ...}

In [34]:
tokenizer.document_count

12230

In [35]:
len(tokenizer.word_index)

17871

In [36]:
sequences=tokenizer.texts_to_sequences(data['Tweets'])

In [37]:
sequences

[[597, 10, 200, 1678, 214, 94, 196, 2524],
 [311,
  2161,
  4023,
  4024,
  189,
  35,
  1007,
  26,
  798,
  905,
  1327,
  9,
  6522,
  6,
  6523,
  3,
  6524,
  146,
  14,
  247,
  193,
  439,
  8,
  1080,
  1,
  3483,
  6,
  2162,
  3097],
 [51],
 [153, 510, 26, 1008, 8, 98, 2322],
 [19,
  250,
  817,
  3098,
  4871,
  4025,
  31,
  2525,
  6525,
  152,
  116,
  12,
  130,
  10123,
  1679,
  242,
  100,
  1,
  2525,
  1518,
  243,
  28,
  250],
 [57, 55, 291, 471, 3, 1, 17],
 [89,
  10124,
  4026,
  927,
  839,
  118,
  13,
  1,
  190,
  2526,
  10125,
  6526,
  16,
  1773,
  190,
  472,
  89,
  976,
  232,
  3,
  4872,
  375,
  35,
  224,
  3,
  89,
  264,
  13,
  2526,
  1,
  6527],
 [10126, 14, 170, 26, 133, 729, 8, 1, 1883, 6, 6528],
 [114, 1, 86, 446, 112, 354, 370, 54, 82, 1169],
 [2, 59, 76, 196, 1259, 14, 659, 5, 50, 1170, 855, 9, 87, 255],
 [1009, 56, 2, 2790, 196],
 [99,
  472,
  28,
  730,
  47,
  2163,
  172,
  1124,
  2323,
  1519,
  32,
  2527,
  72,
  37,
  125,
  1208,
  609,
  64,
  64,
  1,
  2528,
  440,
  1457,
  2163,
  28,
  856,
  10127,
  107,
  323],
 [1680, 12, 3099, 6, 10128, 12, 1681, 6529, 5, 381, 371, 1, 268, 128],
 [45, 58, 857, 21, 8, 12, 858, 25, 10, 46, 64, 291, 670, 1678, 756, 64],
 [106,
  427,
  106,
  219,
  1774,
  117,
  452,
  105,
  27,
  3484,
  288,
  610,
  166,
  8,
  857,
  756,
  4873,
  288,
  30,
  10129,
  6530,
  10130,
  24,
  307,
  18,
  10,
  684,
  4874,
  98,
  10131,
  246,
  6531],
 [584, 69, 61, 182, 99, 40, 8],
 [653, 12, 10132, 171, 191, 6, 10133, 10134],
 [6532, 949, 11, 139, 714, 53, 78, 629, 3100, 4027, 6533, 1587, 39, 3101, 541],
 [48, 14, 498, 248, 31, 18, 5, 2527, 609, 2, 1775, 611, 14],
 [879,
  10135,
  44,
  44,
  4,
  1260,
  2529,
  2164,
  1125,
  10136,
  6534,
  16,
  142,
  1126,
  2791,
  10137,
  77,
  42,
  73,
  6535],
 [22, 757, 53, 598, 29, 103, 162, 10138, 1, 731, 1209, 39, 340],
 [3102, 3, 12, 654, 57, 289, 18, 10],
 [2,
  112,
  19,
  2792,
  36,
  163,
  10,
  346,
  193,
  349,
  54,
  117,
  281,
  138,
  174,
  19,
  4028],
 [125, 499, 351, 261, 4, 1682, 23, 1010, 8, 17, 4, 9, 99, 175],
 [799, 4029, 1011, 23, 10139, 2324, 6536, 1520, 126, 13, 78],
 [87, 441],
 [64, 511, 6537, 90, 253, 621, 4, 174, 692],
 [4875,
  1,
  50,
  212,
  9,
  51,
  6,
  120,
  131,
  2793,
  82,
  234,
  7,
  250,
  2011,
  220,
  21,
  2794,
  18,
  1,
  1328,
  6,
  316,
  1,
  335,
  7,
  294,
  3,
  140,
  1,
  219,
  99,
  26,
  172,
  63,
  4,
  63,
  160,
  128,
  184,
  4,
  4030,
  47,
  1,
  17],
 [1,
  10140,
  214,
  7,
  38,
  139,
  10141,
  29,
  1588,
  818,
  10142,
  231,
  123,
  10143,
  58,
  1127,
  14,
  542,
  36,
  3103,
  82,
  265,
  39,
  182,
  6,
  183,
  500,
  94,
  72,
  928,
  13,
  1588,
  1012,
  143,
  9,
  1,
  880,
  1884,
  16,
  10144],
 [2325,
  1329,
  2326,
  10145,
  2012,
  7,
  349,
  1,
  81,
  177,
  180,
  906,
  8,
  5,
  295,
  60,
  331,
  6,
  14,
  15,
  43,
  181,
  4031,
  671,
  336,
  17,
  18,
  181,
  2795,
  881,
  3104,
  220,
  148,
  15,
  10,
  10146,
  7,
  1039,
  39,
  2,
  49,
  6538,
  10,
  3,
  12,
  3485,
  278,
  6,
  87,
  3486,
  4,
  234,
  10,
  58,
  715,
  63,
  4876,
  2530,
  10147,
  4],
 [525,
  856,
  4032,
  10148,
  8,
  4877,
  10149,
  10150,
  977,
  6539,
  10151,
  1330,
  4878,
  90,
  45,
  10152,
  358,
  1,
  10153,
  6,
  1,
  472,
  10154,
  2327,
  3487,
  2796,
  6540,
  198,
  585,
  90,
  158,
  111,
  453,
  5,
  731,
  8,
  6541,
  6542,
  2531,
  599,
  415,
  144],
 [27,
  65,
  6,
  127,
  26,
  23,
  2,
  96,
  4033,
  6543,
  4,
  266,
  2532,
  2165,
  36,
  1,
  117,
  29],
 [2,
  150,
  3,
  840,
  5,
  929,
  99,
  2533,
  6544,
  929,
  1776,
  3,
  6545,
  23,
  8,
  1,
  191,
  6,
  168,
  17,
  15,
  4879,
  758,
  7,
  6546,
  2534,
  1331],
 [659,
  6,
  1,
  274,
  178,
  10155,
  30,
  385,
  456,
  6547,
  49,
  570,
  8,
  1683,
  29,
  1589,
  6,
  63,
  132,
  930,
  4034,
  1261,
  473,
  3105,
  3,
  115,
  10156,
  16,
  2166,
  859,
  10157],
 [23,
  2,
  498,
  37,
  67,
  12,
  312,
  164,
  292,
  49,
  43,
  101,
  256,
  215,
  630,
  1684,
  371,
  121,
  5,
  164,
  4,
  24,
  37,
  1885,
  139,
  23,
  394,
  210,
  474,
  200,
  91],
 [543,
  197,
  1,
  176,
  95,
  83,
  145,
  30,
  1171,
  1458,
  501,
  6548,
  41,
  3,
  94,
  31,
  8,
  2797,
  33,
  34,
  16,
  10158],
 [141,
  150,
  3,
  352,
  160,
  212,
  660,
  307,
  9,
  907,
  177,
  558,
  685,
  442,
  355,
  1459,
  1262,
  10159],
 [475,
  1685,
  14,
  49,
  2167,
  170,
  10160,
  4035,
  22,
  87,
  9,
  5,
  10161,
  7,
  39,
  2013,
  39,
  11,
  7,
  882],
 [117,
  2535,
  1128,
  2,
  22,
  548,
  3,
  201,
  490,
  5,
  41,
  518,
  155,
  14,
  3,
  27,
  331,
  6,
  14,
  99,
  841,
  4,
  26,
  324,
  13,
  117,
  4880,
  4,
  2798,
  14,
  79,
  732,
  75,
  2536,
  11,
  6549,
  63,
  132,
  559,
  254,
  442,
  1460,
  38,
  76,
  11,
  27,
  536,
  20,
  75,
  314,
  1461,
  19,
  155,
  14],
 [860, 136, 428, 10162, 10163, 84, 6550, 861, 10164],
 [4881, 5, 198, 481, 18, 216, 246, 1, 16],
 [71, 32, 87, 136, 358, 5, 1172, 164, 292, 2168],
 [],
 [80,
  1129,
  1,
  98,
  178,
  171,
  3,
  21,
  12,
  131,
  3488,
  1521,
  401,
  6551,
  16,
  142,
  1263,
  1264,
  4882,
  4036],
 [2014, 3, 89, 4, 88, 1, 3106, 10165, 2169, 4, 125, 1, 81, 819, 152, 225],
 [443,
  2328,
  179,
  23,
  18,
  1,
  10166,
  1522,
  2,
  2328,
  1462,
  57,
  271,
  108,
  14,
  10167,
  4883,
  11,
  48,
  71,
  2170,
  57,
  10168,
  443,
  31],
 [931,
  10169,
  106,
  82,
  180,
  131,
  692,
  512,
  87,
  10170,
  1,
  6552,
  2171,
  10171,
  1886,
  1210,
  6553,
  95,
  83,
  145,
  1208,
  6,
  4884,
  2537,
  6,
  1,
  856,
  2329,
  10172,
  2538,
  4037,
  135,
  2799,
  23,
  10173,
  10174,
  10175,
  10176,
  10177,
  474],
 [6554,
  6555,
  22,
  88,
  1,
  908,
  733,
  842,
  27,
  4,
  167,
  9,
  193,
  250,
  9,
  1,
  2015,
  8,
  1,
  356,
  40,
  58,
  20,
  5,
  1211,
  74,
  142,
  4,
  1,
  250,
  4038,
  622],
 [18, 68, 6556, 47, 10],
 [8,
  6557,
  4885,
  883,
  6,
  293,
  1,
  6558,
  7,
  63,
  202,
  5,
  41,
  362,
  800,
  1463,
  2330,
  1013,
  8,
  1212,
  2331],
 [46],
 [141,
  8,
  12,
  302,
  20,
  2,
  548,
  3,
  279,
  5,
  335,
  3489,
  19,
  151,
  25,
  113,
  90,
  1,
  1887,
  240,
  7,
  141,
  8,
  716,
  115,
  884],
 [10178,
  2800,
  471,
  3,
  142,
  4,
  80,
  672,
  5,
  862,
  212,
  3,
  114,
  5,
  10179,
  10180,
  8,
  549,
  885,
  7,
  10181,
  39,
  6559,
  142,
  10182,
  54,
  1686,
  6,
  61,
  2172,
  11,
  7,
  13,
  801,
  6560,
  759,
  10183,
  10184,
  80,
  16,
  820,
  102,
  10185,
  157],
 [89,
  2801,
  4039,
  123,
  1589,
  1040,
  13,
  14,
  103,
  6561,
  4,
  30,
  70,
  324,
  36,
  103,
  4,
  14,
  26,
  123,
  107,
  909,
  167,
  9,
  309],
 [1687,
  2016,
  3490,
  4886,
  1888,
  454,
  121,
  10186,
  1777,
  6562,
  4887,
  485,
  1391,
  13,
  6563,
  537,
  10187],
 [12, 3491, 886, 10188, 58, 2539, 89],
 [10, 1, 176, 60, 303, 2540, 12, 60, 13, 321, 4040],
 [10, 28, 767, 341, 23, 150, 3, 1332, 12, 887],
 [48,
  5,
  169,
  17,
  950,
  5,
  169,
  17,
  1041,
  13,
  14,
  119,
  14,
  173,
  11,
  5,
  6564,
  2,
  213,
  3,
  173,
  4041,
  204,
  21,
  4888],
 [431, 431, 431, 431],
 [172, 53, 269, 420, 36, 513, 7, 1, 432, 232, 3, 37],
 [2802,
  10189,
  167,
  9,
  123,
  1173,
  3,
  491,
  932,
  199,
  1,
  169,
  3,
  100,
  48,
  14,
  359,
  5,
  282,
  78,
  717,
  308,
  673,
  1213,
  15,
  9,
  205,
  473,
  376,
  3,
  235,
  43,
  1265,
  94,
  734,
  38,
  9,
  5,
  235,
  239,
  106,
  9,
  1042,
  2803,
  888,
  2802,
  77,
  42,
  73,
  10190],
 [],
 [87,
  8,
  1,
  385,
  65,
  4889,
  6,
  191,
  6,
  168,
  7,
  19,
  2332,
  87,
  8,
  1,
  385,
  65,
  17,
  6,
  191,
  6,
  168,
  7,
  19,
  1333,
  87,
  8,
  1,
  385,
  65,
  4889,
  6,
  4042,
  6,
  168,
  7,
  19,
  2332,
  87,
  1889,
  1,
  385,
  65,
  4889,
  6,
  191,
  6,
  168,
  7,
  139,
  2332],
 [447, 889, 274, 246, 124, 411, 91, 1127, 3107, 2804, 1214, 3, 10191],
 [184, 465, 3, 21, 104, 121, 294, 61, 2, 59],
 [863,
  476,
  3,
  4043,
  4,
  1392,
  10,
  90,
  11,
  200,
  32,
  10192,
  7,
  86,
  226,
  1130,
  33,
  34,
  16,
  10193],
 [336, 124],
 [1081,
  6,
  6565,
  279,
  1778,
  1014,
  3,
  578,
  1393,
  358,
  44,
  44,
  6566,
  492,
  3492,
  6,
  452],
 [283,
  1394,
  2,
  59,
  35,
  82,
  1131,
  191,
  6,
  168,
  7,
  51,
  6,
  12,
  27,
  60,
  10194,
  82,
  2,
  22,
  59,
  11,
  181,
  376,
  2,
  242,
  360,
  1464,
  5,
  167,
  441],
 [586, 211, 11, 18, 1, 558, 412],
 [19, 631, 6, 12, 50, 6567, 6568, 4044],
 [1,
  176,
  821,
  6,
  382,
  168,
  28,
  5,
  1590,
  2541,
  10195,
  11,
  10196,
  77,
  73,
  10197],
 [951, 83, 21, 3108, 3, 23, 22, 978, 2, 88, 5, 78, 4045, 13],
 [7,
  843,
  262,
  317,
  185,
  952,
  129,
  623,
  843,
  272,
  3,
  140,
  802,
  6,
  1,
  128,
  6569,
  2017,
  4,
  264,
  172,
  1,
  447,
  428,
  768,
  13,
  262,
  223,
  281,
  33,
  1082,
  10198],
 [11, 7, 24, 1, 130, 60, 15, 1, 550, 760, 52, 599, 265, 5, 600],
 [4890, 155, 4046, 227, 3493, 13, 6570, 8, 1, 357, 293],
 [162,
  780,
  1779,
  26,
  473,
  81,
  3,
  95,
  570,
  3494,
  1043,
  406,
  8,
  29,
  612,
  84,
  6571],
 [267,
  57,
  237,
  275,
  638,
  3495,
  18,
  1,
  17,
  401,
  2805,
  3,
  20,
  5,
  2806,
  3496,
  322,
  3109,
  3497,
  4891,
  4892,
  4047,
  454,
  4893,
  386,
  2542,
  52,
  3110,
  329,
  30,
  3111,
  72,
  350,
  148,
  67,
  135,
  96,
  632,
  10199,
  116,
  1,
  262],
 [],
 [209,
  144,
  7,
  1780,
  8,
  1890,
  64,
  3,
  221,
  275,
  387,
  120,
  2173,
  8,
  10,
  91,
  819,
  74,
  6572,
  454,
  890],
 [844, 303, 4048, 2333],
 [40, 213, 5, 1215, 9, 407, 203, 448],
 [22,
  705,
  475,
  2807,
  185,
  1,
  1083,
  3,
  37,
  13,
  1,
  6573,
  76,
  10200,
  5,
  308,
  17,
  28,
  3,
  315,
  1465,
  6574,
  71,
  19,
  6575,
  3,
  100],
 [2,
  166,
  10,
  398,
  169,
  13,
  78,
  360,
  66,
  560,
  9,
  5,
  1395,
  3,
  235,
  514,
  541,
  78,
  8,
  17,
  486,
  10201],
 [129,
  97,
  8,
  10,
  228,
  212,
  443,
  1891,
  1,
  3498,
  457,
  185,
  45,
  610,
  75,
  15,
  232,
  10,
  336,
  135,
  449,
  1,
  17,
  56,
  14,
  49,
  22,
  387,
  13,
  5,
  6576,
  199,
  4,
  570,
  121,
  124,
  1523],
 [29,
  1,
  256,
  60,
  526,
  1,
  383,
  15,
  110,
  26,
  458,
  66,
  282,
  433,
  70,
  601,
  639,
  1,
  822,
  457,
  131,
  6,
  101,
  46,
  24,
  20,
  257,
  3,
  249,
  493,
  4,
  46,
  24,
  20,
  257,
  3,
  249,
  261,
  189,
  131,
  6,
  101,
  46,
  24,
  20,
  257,
  3,
  249,
  261],
 [1396,
  110,
  7,
  53,
  3112,
  2796,
  2174,
  9,
  4049,
  4050,
  4894,
  6577,
  8,
  1,
  1781,
  2334,
  242,
  11,
  21,
  1132,
  15,
  10202,
  116,
  454,
  6578,
  96,
  979,
  1,
  386,
  6,
  1,
  2334,
  164,
  7,
  6579,
  72,
  125,
  185,
  3,
  1,
  1084,
  2327,
  1125,
  6580,
  160,
  1043,
  7,
  6581,
  674,
  136,
  6582,
  4051,
  3,
  363,
  219],
 [1],
 [57,
  8,
  5,
  519,
  886,
  6,
  718,
  203,
  38,
  25,
  2,
  20,
  3,
  201,
  11,
  28,
  1397,
  57,
  322,
  273,
  47,
  735,
  109,
  13,
  18,
  1133,
  203,
  38,
  2,
  330,
  51,
  128,
  482,
  21,
  5,
  390,
  6,
  11,
  27,
  61,
  5,
  6583,
  33,
  85,
  16,
  4895],
 [167, 267, 9, 1892, 23, 186, 5, 407, 17, 18, 54, 1334, 6584, 3113],
 [1, 86, 108, 768, 29, 1, 300, 6, 10, 7, 1892, 23],
 [1044,
  28,
  265,
  5,
  41,
  164,
  9,
  82,
  2543,
  196,
  217,
  84,
  6585,
  30,
  953,
  2175,
  65,
  2544,
  124,
  4052,
  30,
  322,
  780,
  395,
  198,
  6586,
  2176,
  5,
  1466,
  164],
 [149,
  520,
  149,
  396,
  22,
  1398,
  259,
  36,
  14,
  4,
  141,
  714,
  36,
  35,
  544,
  332,
  388,
  125,
  24,
  8,
  1174,
  46,
  2,
  37,
  3,
  1266,
  12,
  241,
  361,
  6587,
  10,
  7,
  823],
 [153,
  171,
  736,
  14,
  49,
  14,
  170,
  884,
  891,
  114,
  10,
  50,
  4896,
  17,
  397,
  1,
  4897,
  4898,
  1134,
  68,
  2545,
  1,
  769,
  17,
  845,
  74,
  15,
  27,
  3114,
  737,
  11,
  79,
  116,
  19,
  122,
  25,
  2,
  49,
  79,
  15,
  42,
  43,
  545],
 [738,
  27,
  1135,
  3,
  613,
  377,
  1,
  4053,
  85,
  640,
  4,
  108,
  4054,
  15,
  4899,
  31,
  146,
  375,
  70,
  454,
  10203,
  4,
  10204,
  126,
  624,
  10,
  7,
  134,
  781,
  1399,
  13,
  1688,
  102,
  842],
 [1591,
  455,
  48,
  14,
  26,
  24,
  561,
  3,
  739,
  3115,
  351,
  46,
  11,
  2018,
  910,
  35,
  4055,
  317,
  26,
  185,
  4056,
  686,
  25,
  14,
  37,
  224,
  36,
  3115,
  19,
  125,
  499],
 [477,
  416,
  10205,
  477,
  416,
  6588,
  61,
  1,
  2177,
  20,
  45,
  270,
  3,
  1,
  2335,
  6589,
  13,
  1,
  4900,
  10206,
  10,
  7,
  67,
  135,
  32,
  229,
  45,
  1592,
  18,
  316,
  15,
  1524,
  487,
  477,
  416,
  6588],
 [10,
  3499,
  7,
  143,
  2,
  59,
  1525,
  6590,
  641,
  18,
  1,
  1015,
  13,
  11,
  56,
  11,
  22,
  1129,
  3,
  201,
  15,
  12],
 [6591,
  22,
  453,
  117,
  65,
  36,
  12,
  3116,
  402,
  35,
  2336,
  661,
  661,
  49,
  79,
  13,
  42,
  761,
  137,
  3,
  179,
  315,
  1,
  505],
 [1526, 2, 49, 79, 42, 137, 9, 152, 12, 78, 2808],
 [78,
  177,
  22,
  1267,
  5,
  2162,
  614,
  23,
  216,
  6592,
  4057,
  16,
  142,
  1016,
  1264,
  2337],
 [61, 40, 59, 203, 38, 4058, 106, 1467, 288, 64, 94, 196],
 [160,
  60,
  403,
  43,
  10207,
  417,
  23,
  2,
  579,
  1,
  519,
  740,
  56,
  2,
  28,
  228,
  3,
  238,
  6593,
  2338,
  6,
  1,
  625,
  8,
  1,
  40,
  26,
  217,
  84,
  980,
  123,
  625,
  169,
  403,
  16,
  82,
  10208],
 [4901, 227, 41, 9, 1, 10209],
 [3, 6594, 3117, 8, 95, 83, 145, 30, 147, 118, 4059, 6595],
 [432, 2809, 10210, 4060, 131, 4902, 1268],
 [1269,
  412,
  81,
  310,
  1400,
  47,
  527,
  466,
  12,
  718,
  2339,
  14,
  113,
  81,
  1400,
  9,
  824,
  762,
  39,
  562,
  8,
  173,
  6,
  236,
  191,
  204,
  21,
  4903,
  4904],
 [84, 2, 59, 51, 198, 33, 34, 16, 6596],
 [61, 11, 201, 101, 456, 58, 2340, 18, 11, 195, 100, 11, 69, 172, 314, 64],
 [153,
  276,
  67,
  46,
  45,
  264,
  172,
  1,
  4061,
  675,
  633,
  32,
  6597,
  243,
  655,
  675,
  2,
  220,
  642,
  2178,
  4905,
  2178,
  585,
  782,
  32,
  253,
  406,
  36,
  51,
  2179,
  56,
  253,
  205,
  1,
  107,
  232,
  3,
  114,
  11,
  2180,
  7,
  3,
  362,
  1593,
  1,
  1594],
 [2,
  220,
  141,
  687,
  4906,
  3,
  781,
  2341,
  2181,
  1893,
  29,
  221,
  563,
  108,
  9,
  2019],
 [61, 5, 431, 128, 31, 2, 113, 137, 3, 733, 4062, 4, 43, 182, 6, 183],
 [372, 506],
 [931,
  6598,
  78,
  4,
  6599,
  64,
  432,
  6600,
  2795,
  10211,
  16,
  6601,
  3500,
  10212,
  6602,
  6603,
  64,
  10213,
  4063,
  10214,
  6604,
  6605,
  6606,
  1262],
 [5,
  10215,
  1270,
  6607,
  3,
  244,
  14,
  186,
  5,
  346,
  6,
  402,
  80,
  2546,
  546,
  9,
  272,
  3,
  6608,
  1,
  856,
  10216,
  8,
  35,
  731],
 [10217, 26, 1, 372, 240, 15, 49, 1527, 8, 5, 357, 293, 911, 6609, 4, 6610],
 [153, 181, 2182, 13, 172, 190, 2183, 528, 10218, 4, 68, 351, 20, 181],
 [2,
  111,
  5,
  290,
  63,
  60,
  3,
  43,
  2810,
  138,
  4,
  1,
  63,
  2,
  43,
  1,
  17,
  1,
  63,
  6611,
  2,
  112,
  15,
  10,
  17,
  7,
  1,
  228,
  233,
  240],
 [15, 1, 228, 1271, 58, 43, 86, 136],
 [217, 65, 1894, 4, 5, 217, 653, 4901, 21, 19, 289, 51, 128],
 [80, 10219, 423, 13, 763, 2547, 3, 1, 1465, 10220, 16, 80, 10221],
 [87,
  136,
  18,
  12,
  741,
  547,
  88,
  266,
  130,
  912,
  2184,
  358,
  23,
  4,
  68,
  304,
  202,
  359,
  79,
  42,
  864,
  62],
 [65, 93, 91, 17, 14, 88, 1595, 719, 114, 11, 33, 34, 16, 10222],
 [30,
  7,
  518,
  1895,
  39,
  2,
  208,
  59,
  2811,
  1896,
  139,
  187,
  2,
  610,
  166,
  105,
  6,
  101,
  121,
  15,
  693,
  51,
  200,
  981,
  756],
 [4064,
  1136,
  10,
  17,
  364,
  37,
  181,
  63,
  542,
  121,
  1,
  1468,
  54,
  1045,
  10,
  17,
  28,
  5,
  3501],
 [10,
  7,
  5,
  362,
  51,
  90,
  694,
  19,
  4065,
  2,
  58,
  360,
  3,
  6612,
  512,
  197,
  331,
  676,
  2342,
  6613,
  6614],
 [1, 81, 4907],
 [1046,
  174,
  271,
  21,
  19,
  6615,
  48,
  1401,
  74,
  859,
  6616,
  1216,
  13,
  1,
  1137,
  11,
  6617,
  432],
 [10223, 81, 587, 3118, 1782, 111, 1, 860, 688, 6, 71, 742, 743],
 [6618,
  884,
  1780,
  229,
  2,
  202,
  59,
  640,
  546,
  22,
  32,
  6619,
  4,
  6620,
  27,
  6,
  35,
  399,
  2,
  20,
  2,
  720,
  10224,
  4,
  2,
  59,
  11,
  32,
  2,
  59,
  229,
  2,
  6621,
  2,
  24,
  20,
  5,
  411,
  72,
  5,
  190,
  98,
  72,
  5,
  677,
  4066,
  2,
  107,
  3502,
  20,
  24,
  5,
  720,
  4,
  2,
  49,
  24,
  37,
  15,
  229,
  18,
  884,
  1780,
  11,
  2,
  3119,
  14,
  97,
  884],
 [1272, 223, 80, 982, 10225, 1783, 8, 368, 4908, 397, 2333, 16, 2020, 892],
 [366, 263, 59],
 [2, 112, 282, 112, 2343, 271, 783, 10, 165, 39, 434, 39, 11, 1175],
 [24, 107, 298, 85, 1596, 35, 846, 25, 71, 139, 91, 9, 2021],
 [6622,
  209,
  453,
  512,
  5,
  1017,
  6,
  117,
  65,
  17,
  459,
  1,
  250,
  3,
  1171,
  56,
  6623,
  4067,
  11,
  366,
  564,
  11],
 [1128,
  117,
  112,
  40,
  643,
  10,
  55,
  3120,
  97,
  10226,
  23,
  174,
  157,
  174,
  172,
  3121,
  189,
  1,
  386,
  1597,
  26,
  2812,
  45,
  1598,
  4,
  110,
  247,
  1335,
  27,
  641,
  67,
  7,
  10,
  5,
  240],
 [3503, 6624],
 [92, 602, 396, 136, 844, 303, 4909, 6625, 4068],
 [2, 58, 141, 687, 4906, 3, 781, 2341, 2181, 1893, 29, 108, 4, 215, 9, 2019],
 [87, 136, 7, 202, 1, 81, 132, 109, 3, 43, 10227, 8, 1599, 222],
 [1,
  1217,
  954,
  27,
  47,
  27,
  178,
  212,
  116,
  2813,
  212,
  38,
  2344,
  1266,
  1273,
  301,
  16,
  2166,
  177,
  98,
  142,
  77,
  42,
  73,
  6626],
 [695,
  6627,
  6628,
  10228,
  44,
  378,
  11,
  111,
  2180,
  1600,
  125,
  4069,
  355,
  721,
  6629,
  277,
  6630,
  77,
  42,
  73,
  6631],
 [10,
  177,
  47,
  1,
  115,
  4070,
  178,
  7,
  1,
  131,
  514,
  180,
  562,
  47,
  373,
  27,
  164,
  33,
  34,
  16,
  10229],
 [615,
  206,
  28,
  1176,
  764,
  9,
  501,
  4071,
  1,
  1047,
  609,
  4,
  2345,
  1,
  17,
  39,
  434,
  299,
  2,
  242,
  4,
  46,
  2,
  511,
  4910,
  1897,
  10,
  276,
  30],
 [1,
  644,
  390,
  7,
  15,
  110,
  26,
  238,
  63,
  10230,
  10231,
  132,
  3122,
  4,
  3122,
  243,
  6632,
  3,
  207,
  8,
  63,
  10232,
  6633,
  4,
  45,
  6634,
  102,
  27],
 [189,
  2,
  79,
  732,
  75,
  87,
  10,
  17,
  9,
  3504,
  2346,
  194,
  2,
  79,
  329,
  678,
  1601,
  6,
  11],
 [171, 80, 549, 983, 978, 2, 135, 20, 5, 325, 33, 34, 16, 10233],
 [5],
 [],
 [10234,
  7,
  12,
  3123,
  6,
  2022,
  6635,
  4911,
  2814,
  8,
  467,
  191,
  18,
  5,
  4072,
  10235,
  214,
  403,
  10236,
  129,
  623,
  843],
 [500, 1528, 1, 92, 62, 404, 40, 20, 5, 662, 3, 2347, 93, 33, 34, 16, 10237],
 [1330,
  124,
  579,
  19,
  14,
  20,
  139,
  239,
  257,
  3,
  803,
  6,
  91,
  80,
  538,
  14,
  49,
  315,
  18,
  56,
  35,
  893,
  36,
  103,
  127,
  2185,
  630,
  49,
  2548,
  27,
  14,
  63,
  8,
  294,
  22,
  15,
  260,
  171,
  277,
  3505],
 [4912,
  2815,
  14,
  349,
  351,
  261,
  25,
  49,
  14,
  46,
  97,
  97,
  179,
  865,
  31,
  120,
  401,
  219,
  4,
  152,
  984,
  417,
  153,
  3124,
  3,
  46,
  259,
  47,
  6636,
  90,
  94,
  632,
  42,
  23,
  45,
  26,
  294,
  366,
  309,
  97,
  179,
  102,
  45,
  634,
  79,
  1529,
  42,
  894,
  3,
  102,
  5,
  1469,
  32,
  23,
  243,
  7,
  603,
  444],
 [424,
  1218,
  502,
  205,
  425,
  67,
  10,
  907,
  2174,
  979,
  207,
  332,
  7,
  1138,
  24,
  6637],
 [11, 28, 3506, 99, 7, 1, 3507, 1274, 4073, 29, 15, 85],
 [2023, 861, 6, 42, 337],
 [48, 107, 1, 6638, 8, 2816, 218, 1219, 41],
 [507, 804, 78, 7, 109, 3, 92, 14, 18, 905],
 [80,
  933,
  38,
  3508,
  312,
  4074,
  121,
  1,
  1689,
  39,
  53,
  588,
  1,
  2817,
  1018,
  277,
  6639,
  77,
  73,
  6640],
 [3509,
  16,
  2024,
  1470,
  6641,
  4913,
  475,
  4075,
  4914,
  10,
  589,
  2549,
  934,
  2550,
  2,
  22,
  225,
  11,
  8,
  1,

In [38]:
len(sequences[0])

8

In [39]:
len(sequences[1])

29

In [40]:
len(sequences[2])

1

In [41]:
from keras.utils import pad_sequences

In [42]:
sequences=pad_sequences(sequences,padding='pre')

In [43]:
sequences

array([[    0,     0,     0, ...,    94,   196,  2524],
       [    0,     0,     0, ...,     6,  2162,  3097],
       [    0,     0,     0, ...,     0,     0,    51],
       ...,
       [    0,     0,     0, ...,    19,   222,  6167],
       [    0,     0,     0, ...,    42,    73, 17871],
       [    0,     0,     0, ...,   791,  1030,  6491]],
      shape=(12230, 99), dtype=int32)

In [44]:
from tensorflow.keras.layers import SimpleRNN,Dense,Input,Embedding
from tensorflow.keras.models import Sequential

In [45]:
X=sequences

In [46]:
y=data['Sentiment'].values

In [47]:
X

array([[    0,     0,     0, ...,    94,   196,  2524],
       [    0,     0,     0, ...,     6,  2162,  3097],
       [    0,     0,     0, ...,     0,     0,    51],
       ...,
       [    0,     0,     0, ...,    19,   222,  6167],
       [    0,     0,     0, ...,    42,    73, 17871],
       [    0,     0,     0, ...,   791,  1030,  6491]],
      shape=(12230, 99), dtype=int32)

In [48]:
y

array([2, 0, 2, ..., 0, 1, 2], shape=(12230,))

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [51]:
X_train.shape

(9784, 99)

In [52]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(99,1),return_sequences=False))
model.add(Dense(3,activation='softmax'))

c:\Users\Prerna Kumari\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [53]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [55]:
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.3657 - loss: 1.1300 - val_accuracy: 0.3540 - val_loss: 1.0859
Epoch 2/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3655 - loss: 1.0893 - val_accuracy: 0.3622 - val_loss: 1.0848
Epoch 3/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3734 - loss: 1.0880 - val_accuracy: 0.3581 - val_loss: 1.0857
Epoch 4/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.3732 - loss: 1.0914 - val_accuracy: 0.3577 - val_loss: 1.0891
Epoch 5/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3686 - loss: 1.0898 - val_accuracy: 0.3577 - val_loss: 1.0923
Epoch 6/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3552 - loss: 1.0962 - val_accuracy: 0.3602 - val_loss: 1.0965
Epoch 7/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.3618 - loss: 1.0913 - val_accuracy: 0.3602 - val_loss: 1.0942
Epoch 8/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3636 - loss: 1.0954 - val_accuracy: 0.3536 - val_loss: 1.0949
Epoch 9/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.3686 - loss: 1.0925 - val_accuracy: 0.3508 - val_loss: 1.0976
Epoch 10/10
153/153 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.3679 - loss: 1.0923 - val_accuracy: 0.3573 - val_loss: 1.0948

In [56]:
vocab_size=len(tokenizer.word_index) + 1

In [57]:
vocab_size

17872

In [58]:
model_2=Sequential()
model_2.add(Input(shape=(99,)))
model_2.add(Embedding(input_dim=vocab_size,output_dim=64))
model_2.add(Dense(3,activation='softmax'))

In [59]:
model_2.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 99, 64)         │     1,143,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 99, 3)          │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,144,003 (4.36 MB)

 Trainable params: 1,144,003 (4.36 MB)

 Non-trainable params: 0 (0.00 B)

In [60]:
model_final = Sequential([
    Embedding(
        input_dim=vocab_size,
        output_dim=128,
        input_length=99,
        mask_zero=True
    ),
    SimpleRNN(32),
    Dense(3, activation='softmax')
])

c:\Users\Prerna Kumari\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [61]:
model_final.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [62]:
model_final.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [63]:
model_final.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - accuracy: 0.5519 - loss: 0.9488 - val_accuracy: 0.6766 - val_loss: 0.7862
Epoch 2/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.8670 - loss: 0.3792 - val_accuracy: 0.7110 - val_loss: 0.7472
Epoch 3/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.9578 - loss: 0.1317 - val_accuracy: 0.7118 - val_loss: 0.8266
Epoch 4/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - accuracy: 0.9703 - loss: 0.0762 - val_accuracy: 0.7093 - val_loss: 0.9061
Epoch 5/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - accuracy: 0.9750 - loss: 0.0607 - val_accuracy: 0.7081 - val_loss: 0.9619
Epoch 6/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - accuracy: 0.9751 - loss: 0.0539 - val_accuracy: 0.6971 - val_loss: 1.0135
Epoch 7/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - accuracy: 0.9761 - loss: 0.0491 - val_accuracy: 0.6913 - val_loss: 1.0964
Epoch 8/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - accuracy: 0.9750 - loss: 0.0478 - val_accuracy: 0.6885 - val_loss: 1.1492
Epoch 9/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 20ms/step - accuracy: 0.9762 - loss: 0.0482 - val_accuracy: 0.6509 - val_loss: 1.2624
Epoch 10/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - accuracy: 0.9673 - loss: 0.0688 - val_accuracy: 0.6823 - val_loss: 1.1628
Epoch 11/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - accuracy: 0.9742 - loss: 0.0530 - val_accuracy: 0.6827 - val_loss: 1.1722
Epoch 12/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - accuracy: 0.9757 - loss: 0.0455 - val_accuracy: 0.6877 - val_loss: 1.2065
Epoch 13/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9770 - loss: 0.0441 - val_accuracy: 0.6913 - val_loss: 1.2344
Epoch 14/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 13s 60ms/step - accuracy: 0.9769 - loss: 0.0434 - val_accuracy: 0.6913 - val_loss: 1.2650
Epoch 15/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - accuracy: 0.9771 - loss: 0.0433 - val_accuracy: 0.6897 - val_loss: 1.2944
Epoch 16/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - accuracy: 0.9775 - loss: 0.0424 - val_accuracy: 0.6836 - val_loss: 1.3012
Epoch 17/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - accuracy: 0.9773 - loss: 0.0428 - val_accuracy: 0.6872 - val_loss: 1.3289
Epoch 18/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - accuracy: 0.9759 - loss: 0.0428 - val_accuracy: 0.6840 - val_loss: 1.3531
Epoch 19/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9771 - loss: 0.0421 - val_accuracy: 0.6844 - val_loss: 1.3497
Epoch 20/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 65ms/step - accuracy: 0.9769 - loss: 0.0422 - val_accuracy: 0.6901 - val_loss: 1.3512
Epoch 21/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9765 - loss: 0.0426 - val_accuracy: 0.6872 - val_loss: 1.3660
Epoch 22/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9768 - loss: 0.0419 - val_accuracy: 0.6836 - val_loss: 1.3761
Epoch 23/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 67ms/step - accuracy: 0.9768 - loss: 0.0415 - val_accuracy: 0.6823 - val_loss: 1.4029
Epoch 24/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 19s 59ms/step - accuracy: 0.9768 - loss: 0.0419 - val_accuracy: 0.6791 - val_loss: 1.4174
Epoch 25/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9767 - loss: 0.0414 - val_accuracy: 0.6860 - val_loss: 1.4564
Epoch 26/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9772 - loss: 0.0418 - val_accuracy: 0.6827 - val_loss: 1.4231
Epoch 27/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9753 - loss: 0.0412 - val_accuracy: 0.6799 - val_loss: 1.4645
Epoch 28/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9771 - loss: 0.0409 - val_accuracy: 0.6836 - val_loss: 1.4489
Epoch 29/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9766 - loss: 0.0419 - val_accuracy: 0.6750 - val_loss: 1.4425
Epoch 30/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 61ms/step - accuracy: 0.9769 - loss: 0.0411 - val_accuracy: 0.6733 - val_loss: 1.4551
Epoch 31/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9781 - loss: 0.0407 - val_accuracy: 0.6827 - val_loss: 1.4652
Epoch 32/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9769 - loss: 0.0406 - val_accuracy: 0.6799 - val_loss: 1.4823
Epoch 33/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - accuracy: 0.9775 - loss: 0.0411 - val_accuracy: 0.6672 - val_loss: 1.4869
Epoch 34/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 62ms/step - accuracy: 0.9778 - loss: 0.0409 - val_accuracy: 0.6766 - val_loss: 1.4801
Epoch 35/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9773 - loss: 0.0405 - val_accuracy: 0.6742 - val_loss: 1.4985
Epoch 36/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 59ms/step - accuracy: 0.9780 - loss: 0.0407 - val_accuracy: 0.6746 - val_loss: 1.5236
Epoch 37/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9769 - loss: 0.0403 - val_accuracy: 0.6717 - val_loss: 1.5131
Epoch 38/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9775 - loss: 0.0402 - val_accuracy: 0.6795 - val_loss: 1.5209
Epoch 39/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - accuracy: 0.9769 - loss: 0.0403 - val_accuracy: 0.6676 - val_loss: 1.5437
Epoch 40/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9715 - loss: 0.0550 - val_accuracy: 0.6075 - val_loss: 1.6388
Epoch 41/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9346 - loss: 0.1610 - val_accuracy: 0.6684 - val_loss: 1.1799
Epoch 42/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 57ms/step - accuracy: 0.9744 - loss: 0.0531 - val_accuracy: 0.6844 - val_loss: 1.1939
Epoch 43/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9775 - loss: 0.0418 - val_accuracy: 0.6860 - val_loss: 1.2269
Epoch 44/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9764 - loss: 0.0412 - val_accuracy: 0.6872 - val_loss: 1.2517
Epoch 45/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9775 - loss: 0.0405 - val_accuracy: 0.6901 - val_loss: 1.2758
Epoch 46/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9770 - loss: 0.0402 - val_accuracy: 0.6909 - val_loss: 1.2948
Epoch 47/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9778 - loss: 0.0401 - val_accuracy: 0.6909 - val_loss: 1.3211
Epoch 48/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9768 - loss: 0.0401 - val_accuracy: 0.6934 - val_loss: 1.3363
Epoch 49/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9767 - loss: 0.0399 - val_accuracy: 0.6934 - val_loss: 1.3451
Epoch 50/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9769 - loss: 0.0403 - val_accuracy: 0.6922 - val_loss: 1.3661
Epoch 51/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9764 - loss: 0.0399 - val_accuracy: 0.6946 - val_loss: 1.3719
Epoch 52/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9771 - loss: 0.0401 - val_accuracy: 0.6922 - val_loss: 1.3879
Epoch 53/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9770 - loss: 0.0400 - val_accuracy: 0.6926 - val_loss: 1.4007
Epoch 54/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9770 - loss: 0.0400 - val_accuracy: 0.6942 - val_loss: 1.4110
Epoch 55/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9775 - loss: 0.0400 - val_accuracy: 0.6897 - val_loss: 1.4271
Epoch 56/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9774 - loss: 0.0397 - val_accuracy: 0.6897 - val_loss: 1.4162
Epoch 57/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9774 - loss: 0.0400 - val_accuracy: 0.6913 - val_loss: 1.4466
Epoch 58/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9784 - loss: 0.0401 - val_accuracy: 0.6860 - val_loss: 1.4518
Epoch 59/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 60ms/step - accuracy: 0.9767 - loss: 0.0400 - val_accuracy: 0.6877 - val_loss: 1.4690
Epoch 60/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9766 - loss: 0.0398 - val_accuracy: 0.6852 - val_loss: 1.4673
Epoch 61/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9762 - loss: 0.0401 - val_accuracy: 0.6975 - val_loss: 1.4606
Epoch 62/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9773 - loss: 0.0398 - val_accuracy: 0.6946 - val_loss: 1.4828
Epoch 63/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9783 - loss: 0.0395 - val_accuracy: 0.6889 - val_loss: 1.5056
Epoch 64/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 60ms/step - accuracy: 0.9775 - loss: 0.0399 - val_accuracy: 0.6864 - val_loss: 1.4890
Epoch 65/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 62ms/step - accuracy: 0.9773 - loss: 0.0397 - val_accuracy: 0.6922 - val_loss: 1.4953
Epoch 66/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 62ms/step - accuracy: 0.9773 - loss: 0.0399 - val_accuracy: 0.6897 - val_loss: 1.5070
Epoch 67/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 52ms/step - accuracy: 0.9758 - loss: 0.0396 - val_accuracy: 0.6905 - val_loss: 1.5172
Epoch 68/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 62ms/step - accuracy: 0.9772 - loss: 0.0396 - val_accuracy: 0.6885 - val_loss: 1.5219
Epoch 69/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9772 - loss: 0.0398 - val_accuracy: 0.6913 - val_loss: 1.5394
Epoch 70/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9764 - loss: 0.0400 - val_accuracy: 0.6913 - val_loss: 1.5295
Epoch 71/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - accuracy: 0.9779 - loss: 0.0396 - val_accuracy: 0.6881 - val_loss: 1.5346
Epoch 72/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 12s 65ms/step - accuracy: 0.9779 - loss: 0.0393 - val_accuracy: 0.6864 - val_loss: 1.5505
Epoch 73/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 14s 92ms/step - accuracy: 0.9762 - loss: 0.0395 - val_accuracy: 0.6844 - val_loss: 1.5577
Epoch 74/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 14s 88ms/step - accuracy: 0.9768 - loss: 0.0392 - val_accuracy: 0.6872 - val_loss: 1.5735
Epoch 75/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 19s 77ms/step - accuracy: 0.9773 - loss: 0.0394 - val_accuracy: 0.6864 - val_loss: 1.5801
Epoch 76/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9773 - loss: 0.0393 - val_accuracy: 0.6852 - val_loss: 1.5841
Epoch 77/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 71ms/step - accuracy: 0.9773 - loss: 0.0394 - val_accuracy: 0.6836 - val_loss: 1.6051
Epoch 78/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - accuracy: 0.9774 - loss: 0.0394 - val_accuracy: 0.6783 - val_loss: 1.6010
Epoch 79/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - accuracy: 0.9781 - loss: 0.0393 - val_accuracy: 0.6742 - val_loss: 1.6033
Epoch 80/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9784 - loss: 0.0392 - val_accuracy: 0.6783 - val_loss: 1.6046
Epoch 81/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 7s 45ms/step - accuracy: 0.9777 - loss: 0.0392 - val_accuracy: 0.6811 - val_loss: 1.6343
Epoch 82/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9772 - loss: 0.0392 - val_accuracy: 0.6754 - val_loss: 1.6165
Epoch 83/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9778 - loss: 0.0390 - val_accuracy: 0.6836 - val_loss: 1.6402
Epoch 84/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - accuracy: 0.9770 - loss: 0.0390 - val_accuracy: 0.6713 - val_loss: 1.6251
Epoch 85/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9615 - loss: 0.0815 - val_accuracy: 0.6713 - val_loss: 1.3739
Epoch 86/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9685 - loss: 0.0647 - val_accuracy: 0.6881 - val_loss: 1.3144
Epoch 87/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 60ms/step - accuracy: 0.9787 - loss: 0.0416 - val_accuracy: 0.6942 - val_loss: 1.3341
Epoch 88/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 62ms/step - accuracy: 0.9788 - loss: 0.0393 - val_accuracy: 0.6930 - val_loss: 1.3505
Epoch 89/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 62ms/step - accuracy: 0.9780 - loss: 0.0390 - val_accuracy: 0.6926 - val_loss: 1.3688
Epoch 90/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - accuracy: 0.9777 - loss: 0.0389 - val_accuracy: 0.6917 - val_loss: 1.3903
Epoch 91/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - accuracy: 0.9778 - loss: 0.0388 - val_accuracy: 0.6901 - val_loss: 1.4024
Epoch 92/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9773 - loss: 0.0388 - val_accuracy: 0.6942 - val_loss: 1.4161
Epoch 93/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - accuracy: 0.9777 - loss: 0.0388 - val_accuracy: 0.6942 - val_loss: 1.4247
Epoch 94/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - accuracy: 0.9773 - loss: 0.0388 - val_accuracy: 0.6954 - val_loss: 1.4339
Epoch 95/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9778 - loss: 0.0389 - val_accuracy: 0.6913 - val_loss: 1.4416
Epoch 96/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 57ms/step - accuracy: 0.9773 - loss: 0.0389 - val_accuracy: 0.6934 - val_loss: 1.4521
Epoch 97/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 11s 62ms/step - accuracy: 0.9782 - loss: 0.0390 - val_accuracy: 0.6917 - val_loss: 1.4609
Epoch 98/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 10s 65ms/step - accuracy: 0.9778 - loss: 0.0390 - val_accuracy: 0.6930 - val_loss: 1.4705
Epoch 99/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 9s 60ms/step - accuracy: 0.9784 - loss: 0.0390 - val_accuracy: 0.6946 - val_loss: 1.4778
Epoch 100/100
153/153 ━━━━━━━━━━━━━━━━━━━━ 8s 54ms/step - accuracy: 0.9767 - loss: 0.0388 - val_accuracy: 0.6950 - val_loss: 1.4854

In [64]:
import pickle

In [65]:
with open('tokenizer.pkl','wb')as file:
    pickle.dump(tokenizer,file)

In [66]:
model_final.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.